### ISSUE TITLE
How to have log / debug information when using the GitHub App

### ISSUE THREAD

**Issue by kdisneur** [toolmantim/tap-release#82]
Hi, 

I just tried to install the application using GitHub Apps.
I gave permission to my homebrew repository and my code repository.
I then added a configuration file, pushed it to a branch and created a release.

Nothing happened. 

I probably misconfigured something but I have no idea how I can debug / have access to  some logs from the GitHub App.

Could you help somehow? 

Thanks!

**Comment by kdisneur** [comment]
I finally deployed my own instance so I could have logs easily accessible.

**Comment by toolmantim** [comment]
Sorry, seems I lost my half-written reply to you! Glad you got it working, but sorry for the delayed reply.

The state of config error reporting for Probot isn’t great.

I was going to ask if you were on the GitHub Actions beta? Because if so, I was looking to package this into an Action (which is fairly easy thanks to Probot) and gives you logs, as it runs in your own Actions containers.

**Comment by kdisneur** [comment]
Thanks for the reply :) I used the `Install` button on the README so I was using your hosted version I guess.

**Comment by toolmantim** [comment]
I meant, do you have access to the Actions beta?

**Comment by kdisneur** [comment]
ah! yes I do.
